# Generated by Django 4.2.5 on 2023-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_url', models.CharField(blank=True, default=False, max_length=2083)),
                ('book_available', models.BooleanField(default=False)),
            ],
        ),
    ]
